# Generated by Django 2.1.4 on 2019-05-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
    ]
